# This file is part of the Consumer API Example.
#
# Copyright (C) 2023 Serghei Iakovlev <egrep@protonmail.ch>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

python:
  - any: ['consumer/**/*']

tests:
  - any: ['tests/**/*']

github_actions:
  - any: ['.github/**/*']

contracts:
  - any: ['tests/pacts/*.json']

documentation:
  - '*.rst'
