# This file is part of the Consumer API example.
#
# Copyright (C) 2023 Serghei Iakovlev <egrep@protonmail.ch>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

version: '3.9'

services:

  # A PostgreSQL database for the Broker to store Pacts
  # and verification results.
  postgres:
    image: postgres:15
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d pact -U pact' ]
      interval: 3s
      timeout: 2s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - pact-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pact
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pact

  # The Pact Broker
  broker_app:
    image: pactfoundation/pact-broker:latest
    ports:
      - '80:9292'
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    environment:
      PACT_BROKER_DATABASE_ADAPTER: postgres
      PACT_BROKER_DATABASE_USERNAME: pact
      PACT_BROKER_DATABASE_PASSWORD: secret
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: pact
      PACT_BROKER_BASIC_AUTH_USERNAME: pactbroker
      PACT_BROKER_BASIC_AUTH_PASSWORD: pactbroker
    # The Pact Broker provides a healthcheck endpoint which we will use to wait
    # for it to become available before starting up
    healthcheck:
      test: [ 'CMD', 'wget', '-q', '--tries=1', '--spider', 'http://pactbroker:pactbroker@localhost:9292/diagnostic/status/heartbeat' ]
      interval: 1s
      timeout: 2s
      retries: 10

volumes:
  pact-data:
    driver: local
