# This file is part of the Consumer API Example.
#
# Copyright (C) 2023 Serghei Iakovlev <egrep@protonmail.ch>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

name: Unit Tests

on:
  push:
    branches-ignore:
      # These should always correspond to pull requests, so ignore them for
      # the push trigger and let them be triggered by the pull_request
      # trigger, avoiding running the workflow twice.  This is a minor
      # optimization so there's no need to ensure this is comprehensive.
      - 'dependabot/**'

  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Test Consumer
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup cache on Linux
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up virtualenv
        run: make init

      - name: Install dependencies
        run: make install

      - name: Run unit tests with coverage
        run: make test

      - name: Combine coverage reports
        run: make ccov

      - uses: codecov/codecov-action@v3.1.4
        if: success()
        with:
          fail_ci_if_error: false
          verbose: true
          name: codecov-umbrella
          flags: unittests
          env_vars: OS,PYTHON
